DECLARE
TABLE_NAME VARCHAR(50);
PRODUCT_KEY INTEGER;
TIME_KEY INTEGER;
STORE_KEY INTEGER;
PRODUCT VARCHAR(50);
CATEGORY VARCHAR(50);
DEPARTMENT VARCHAR(50);
STORE_NAME VARCHAR(50);
TERRITORY VARCHAR(50);
REGION VARCHAR(50);
DATES DATE;
MONTH VARCHAR(50);
QUARTER INTEGER;
YEAR INTEGER;
UNIT_SALES INTEGER;
SALES_DOLLARS INTEGER;
BEGIN
TABLE_NAME := '&TABLE_NAME';
CASE TABLE_NAME
WHEN 'PRODUCT' THEN
INSERT INTO PRODUCT VALUES(&PRODUCT_KEY,'&PRODUCT','&CATEGORY','&DEPARTMENT');
WHEN 'STORE' THEN
INSERT INTO STORE VALUES(&STORE_KEY,'&STORE_NAME', '&TERRITORY', '&REGION');
WHEN 'TIME' THEN
INSERT INTO TIME VALUES(&TIME_KEY, '&DATES', '&MONTH', &QUARTER, &YEAR);
WHEN 'SALES_FACTS' THEN
INSERT INTO SALES_FACTS VALUES(&PRODUCT_KEY, &TIME_KEY, &STORE_KEY, &UNIT_SALES, &SALES_DOLLARS);
END CASE;
END;
/